### ISSUE TITLE
missing-playwright-await rule: Suppress rule when inside Promise.all array

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [playwright-community/eslint-plugin-playwright#100]
Hi,

so i have this use-case:

```
  await Promise.all([
    // eslint-disable-next-line playwright/missing-playwright-await
    expect(checkbox).toHaveAttribute('aria-selected', 'true'),
    checkbox.check(),
  ]);
```

As you can see i had to suppress the rule for that assertion.
It would be nice if the rule could detect that as we are inside a Promise.all we don't have to await on that line.

Thank you.

**Comment by mskelton** [comment]
What's the use case for that?  Why not just write it like this?

```js
await checkbox.check()
await expect(checkbox).toHaveAttribute('aria-selected', 'true')
```

**Comment by AndreaPontrandolfo** [comment]
Yes, you are right, this works too. I think i tried this before and it was somewhat flaky (like there was a race condition or something), but retrying it now multiple times, it's perfectly fine. Maybe there was something else wrong in my code that i eventually fixed, not sure.

Anyway, thank you, closing this.
