### ISSUE TITLE
Add `no-nth-methods` rule

### ISSUE THREAD

**Issue by unlikelyzero** [playwright-community/eslint-plugin-playwright#119]
We've had a few bad locators/selectors sneak into our code and it would be great if we could provide a linting rule to detect them.

Examples.

>> nth
.nth()
.first()

More https://www.checklyhq.com/learn/headless/basics-selectors/#examples-of-bad-selectors

**Comment by mskelton** [comment]
@unlikelyzero I'm not sure I understand the issue.  What's wrong with nth and first?  I totally agree that you don't want to over depend on them, but I'm also not sure a rule to prevent them is the right option.

**Comment by piotr-kwiatkowski** [comment]
It would be nice to add an additional rule for methods `.first()`, `.last()`, `.nth()`.

As [Playwright's documentation](https://playwright.dev/docs/locators#strictness) states they are **not recommended**:

> You can explicitly opt-out from strictness check by telling Playwright which element to use when multiple elements match, through [locator.first()](https://playwright.dev/docs/api/class-locator#locator-first), [locator.last()](https://playwright.dev/docs/api/class-locator#locator-last), and [locator.nth()](https://playwright.dev/docs/api/class-locator#locator-nth). These methods are not recommended because when your page changes, Playwright may click on an element you did not intend.

And it would be nice to set a warning for using them.
