### ISSUE TITLE
Suggestion: make sure context.close() is called on browser.newContext()

### ISSUE THREAD

**Issue by AntonNiklasson** [playwright-community/eslint-plugin-playwright#121]
I just run into an with video recordings not being saved as expected from a scenario. I realised I hadn't called `context.close()` on a context I created earlier in the test using `browser.newContext()`.

It would have been nice to get an error no that. I think it should be doable as a rule? I'd love to take a stab at it, I've written a few rules beofre. I just want to validate the idea before jumping into code.

**Comment by mskelton** [comment]
Sorry for not responding earlier, I missed this.  This feels like a pretty niche rule given that most people using this are likely using `@playwright/test` which in general abstracts many of these details so you don't have to worry about them.

**Comment by mskelton** [comment]
Closing this as not planned, this is super niche as most people should use `@playwright/test`.
