### ISSUE TITLE
Add `no-class-selectors` rule

### ISSUE THREAD

**Issue by unlikelyzero** [playwright-community/eslint-plugin-playwright#123]
We're going to be leaning into an accessibility focused locator strategy (`getByRole`, specificially) and would like a rule to detect locators which reference css classnames. CSS Classnames aren't interpreted by Assistive Technologies.

**Comment by EvgenyOrekhov** [comment]
I would like it to be a more general rule - `prefer-user-facing-locators`, that forbids any usage of `page.locator()`, and encourages usage of `page.getByRole()` and other user-facing locators. Like [this example from best practices](https://playwright.dev/docs/best-practices#prefer-user-facing-attributes-to-xpath-or-css-selectors).

**Comment by Haberkamp** [comment]
How's the state of this issue? I'd be down to help with writing the rule.
