### ISSUE TITLE
"Expect must have a corresponding matcher call" triggered for custom functions with "expect" in the name

### ISSUE THREAD

**Issue by tomdohnal** [playwright-community/eslint-plugin-playwright#153]
We have a bunch of helper functions that are called something like `expectPayButtonToBeEnabled` that wrap several `expect(...).toBe...` statements that we call in our tests like `expectPayButtonToBeEnabled()`.

However, the `Expect must have a corresponding matcher call` warning is triggered when we try to use them.

Would it be possible to only match `expect` calls and not calls to any functions that begin with the word `expect`?

Or is this behavior intentional?

If not, i'm happy to send a PR!

**Comment by tomdohnal** [comment]
I assume the answer is here: https://github.com/playwright-community/eslint-plugin-playwright/issues/152#issuecomment-1614665667.

**Comment by mskelton** [comment]
Actually, I think a slight change may be possible. For expect, I updated the regex to `(^expect|Expect)$` so that we won't catch methods like `expectPayButtonToBeEnabled` but we still catch expect variants such as `softExpect`.
