### ISSUE TITLE
Ability to extend/override assertion function names

### ISSUE THREAD

**Issue by sarayourfriend** [playwright-community/eslint-plugin-playwright#154]
Related to #67.

`eslint-plugin-jest`'s `expect-expect` rule has a configuration option for overwriting the list of assertion function names. This is handy if you write functions that contain complex assertions reusable across several different tests. This plugin's `expect-expect` does not have this option, however.

If acceptable, I can try to open a PR to add this feature.

**Comment by mskelton** [comment]
I'd be open to that, yep!
