### ISSUE TITLE
playwright/expect-expect with expect in fixtures gives warning

### ISSUE THREAD

**Issue by sheuertz** [playwright-community/eslint-plugin-playwright#161]
Hi,

I've updated to the latest, and I'm getting lint warnings for `playwright/expect-expect` in some of my tests where I have a bunch of custom fixtures. There is no expect directly in the top level test, but there are in each of the fixtures. I've written the fixtures due to the amount of code reuse in the application. So, for example, our test looks like:
```
test('Create Document', async ({
  context,
  page,
  homePage,
  customerInvoice,
  cashControl,
  documentSearch,
  paymentApplication,
  paymentApplicationAdjustment
}) => {
  await homePage.goto();
  await homePage.getSidebar().jumpTo('Customer Invoice');
  await customerInvoice.awaitInitialLoad();
  const docId= await customerInvoice.createRequiredCustomerInvoice([data here]);
  ... more processing here ...
};
```
So each of the fixtures like homePage, customerInvoice, etc, have expect within them. Is my only option at this time to disable the rule for these top level drivers?

Thanks!

**Comment by mskelton** [comment]
This is kind of the point of the expect-expect rule. It's not clear in the code you've written that there are any expectations. I would highly recommend against using expectations in page objects as it makes your code much less clear.

The way I think about it is that page objects drive the test and then expectations ensure your app does what it should.

**Comment by eemelipa** [comment]
Sounds like https://github.com/playwright-community/eslint-plugin-playwright/issues/154 would help with this

**Comment by sheuertz** [comment]
That's fair. I'm just trying to reduce duplication since these will be used in many many different tests.

**Comment by dvag-sebastian-goeb** [comment]
Maybe it would be possible to statically analyse the called methods for existence of `expect`s? Then only when there is provably at least one execution path that leads to no `expect` would the warning trigger. But I'm not familiar enough with static analysis to say how easy or hard this is to do. I do know that many IDEs provide this level of insight in some cases (e.g. warnings that some parameter of a function is unused by all callers).

Some very nice features of having expectations in page object methods is that
- a complex assertion can be wrapped in a test.step(), so it's readable as one step in the html report.
- testing (especially integration testing) complex flows becomes a lot more manageable.

By the second I mean the following: at work we have these SAP Luigi microfrontends, which are basically independent SPAs that are hosted on different domains and are stitched together via iFrames into a cohesive whole.

Integration testing a long flow across multiple of the SPAs can then be done like this:
```
// "page"-objects, which represents an entire SPA and encapsulate page objects for the individual pages
spa1App.someComplexSetup();
spa2App.doSomeSubflow();
spa3App.verifyThatHappyPathFlowStillWorks();
```

or possibly with one of these levels broken up to test an interesting bit directly and surround it with happy-path one-liners:
```
// "page"-objects, which represents an entire SPA and encapsulate page objects for the individual pages
spa1App.someComplexSetup();
... lots of individual steps and assertions directly in the test
spa3App.verifyThatHappyPathFlowStillWorks();
```

**Comment by mskelton** [comment]
> I do know that many IDEs provide this level of insight in some cases (e.g. warnings that some parameter of a function is unused by all callers).

That typically requires type information which is something that static analysis with ESLint doesn't provide. Perhaps it's possible using `@typescript-eslint`, I'm honestly not sure.

I'll again re-iterate that placing expect statements in page objects is NOT recommended.  That's my entire point in this thread. I'm trying to convey what is and isn't recommended. If you decide to use a different pattern for you app, that's totally fine, but the ESLint rules this plugin provides are aimed at helping you write code according to recommendations we have from experience writing Playwright tests and from recommendations from the Playwright team itself.

For your use case, you're probably best to just disable the rule if you want to continue using page objects the way you are. There's nothing wrong with disabling this rule if it doesn't fit your coding standards. I still would recommend rethinking `expect`s in page objects, but again that's your decision.
