### ISSUE TITLE
error Unexpected use of networkidle playwright/no-networkidle

### ISSUE THREAD

**Issue by krishna01012002** [playwright-community/eslint-plugin-playwright#163]
Please suggest why networkidle is should not be used , what could be the alteratives

**Comment by mskelton** [comment]
From the Playwright docs:

> DISCOURAGED consider operation to be finished when there are no network connections for at least 500 ms. Don't use this method for testing, rely on web assertions to assess readiness instead.

Use locator assertions instead

https://playwright.dev/docs/api/class-locatorassertions
