### ISSUE TITLE
No assertion error

### ISSUE THREAD

**Issue by Dinh246** [playwright-community/eslint-plugin-playwright#170]
Hello guys, as you all may know, playwright TS introduced expect configuration in a couple updates ago. 
I've faced an issue when I use this kind of update, for instance, 
`const softAssertion = expect.configure({ soft: true })
test(`test A`, async() => {
await softAssertion(locA).toBeVisible();
})`,
My test then warning me that there's no assertion in test and that annoying I should let at least one expect in the test to bypass it. Please cover this.

**Comment by mskelton** [comment]
The plugin expects to find `expect` somewhere in the name of the function, so `expect()` or `softExpect` are both valid ways to write it. My recommendation would be to rename `softAssertion` to `softExpect`.

You can also use `additionalAssertFunctionNames` which is documented in the readme.

Hope that helps!
