### ISSUE TITLE
Feature request: Prefer Auto Retrying Assertions

### ISSUE THREAD

**Issue by dylang** [playwright-community/eslint-plugin-playwright#175]
We've found that tests can be less flaky and easier to maintain by using [Auto Retrying Assertions](https://playwright.dev/docs/test-assertions#auto-retrying-assertions).

## Feature Request: `prefer-auto-retry-assertions`

Depending on how customizable we want to make this, this rule could let developers choose which [Non-retrying-assertions](https://playwright.dev/docs/test-assertions#non-retrying-assertions) are not allowed, and/or maybe auto-fix or suggest a better way to write the assertion. 

## Example

* Error: `expect(await locator.isVisible()).toBe(true);`
* Fix: `await expect(locator).toBeVisible();`

**Comment by mskelton** [comment]
We already support this via the `prefer-web-first-assertions` rule.

https://github.com/playwright-community/eslint-plugin-playwright/blob/main/docs/rules/prefer-web-first-assertions.md

**Comment by dylang** [comment]
Awesome, thank you, I didn't understand what `web-first` meant.
