### ISSUE TITLE
Feature Request: Add option to `no-raw-locators` to allow certain selectors

### ISSUE THREAD

**Issue by weikinhuang** [playwright-community/eslint-plugin-playwright#183]
It would be useful to allow locators like `[aria-busy="false"]` and a few other raw locators that are currently not built in to playwright, as opposed to testing library aria selectors.

My suggestion would be to have a list of selectors strings as part of the options to the rule

```js
{
 'no-raw-locators': [
    'error',
    {
      allowed: [
        '[aria-busy="false"]'
      ]
    }
  ],
} 
```

I would love to enable this rule, but my current use case is something like so:

```typescript
page.getByRole('navigation').and(page.locator('[aria-busy="false"]'));
```

**Comment by bryanpackman** [comment]
This would be useful. I came across something similar when trying to located an embed on the page. Iframe's don't have a native aria role, so I had to use 

`page.locator('iframe')`

**Comment by weikinhuang** [comment]
thanks @mskelton!

**Comment by EvgenyOrekhov** [comment]
@bryanpackman Iframes do support an accessible name via `name` attribute. Make sure to set `name` for your iframe, and then you can use `page.frame('Your iframe name')`.
