### ISSUE TITLE
[Feature]: New rule: avoid-discouraged

### ISSUE THREAD

**Issue by mxschmitt** [playwright-community/eslint-plugin-playwright#187]
Playwright annotates methods with being discouraged like `page.waitForSelector` in the source docs (microsoft/playwright). They will be surfaced to the user in the docs and rendered in the generated types.d.ts.

It would be great to scrape this list and treat the as warnings in the end, might require a typescript-eslint plugin instead, so we have access to type information.

**Comment by mskelton** [comment]
@mxschmitt I'm not sure a single rule makes the most sense, I like the granularity of our rules to let people disable specific rules easily. That said, implementing a `no-waitForSelector` rule is a good idea.

**Comment by mxschmitt** [comment]
Sounds valid as well, periodically go over the discouraged methods from the Playwright side and implement them each by each as an individual rule.

**Comment by mskelton** [comment]
Cool, going to close this one for now then.
