### ISSUE TITLE
[Question] How to implement and add a custom rule?

### ISSUE THREAD

**Issue by python012** [playwright-community/eslint-plugin-playwright#195]
Hi, is it possible to implement and add custom rule? For example, I'd like to add a rule that, each test name need start with a specific Jira key code, like `FEAT-6792 user can see recommendations`, I'd like to define a regex, which each test name shall match with.

```
test('FEAT-6792 user can see recommendations', async ({}, testInfo) => {
  testInfo.annotations.push({ type: 'test_key', description: 'FEAT-6792' });
  //...
});

```

**Comment by mskelton** [comment]
@python012 This is supported uston the `valid-title` rule and the `mustMatch` option.

https://github.com/playwright-community/eslint-plugin-playwright/blob/main/docs/rules/valid-title.md#mustmatch--mustnotmatch

**Comment by python012** [comment]
Thank You! @mskelton
