### ISSUE TITLE
[Feature] Warn on use of .getByTitle()

### ISSUE THREAD

**Issue by unlikelyzero** [playwright-community/eslint-plugin-playwright#196]
We are in the process of migrating our codebase to use the `no-raw-locators` rule to enforce a consistent, accessibility-focused experience for testers.

Through this effort, we found that HTML Titles are now discouraged on our application as they [seem to be elsewhere](https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/). It would be nice to have the ability to warn on the use of [getByTitle](https://playwright.dev/docs/api/class-page#page-get-by-title)

**Comment by vladkrasn** [comment]
@mskelton I am getting an error when tryiing to enable this rule, can it be because it was not added to src/index.ts?

**Comment by mskelton** [comment]
@vladkrasn Just pushed a fix and a test so this won't be an issue in the future!
