### ISSUE TITLE
[New Rule] Add a rule to verify that a locator has an action verb / method / assertion

### ISSUE THREAD

**Issue by unlikelyzero** [playwright-community/eslint-plugin-playwright#197]
We're in process of migrating from page.click('badlocator') to page.goodlocatorstrategy().click() and are finding it difficult to be precise when changing 700+ references. It would be great if we could ensure that the locator had an action verb / method / assertion at the end of a locator

**Comment by python012** [comment]
do you mean the rule to make sure each locator variable is used/called in a function? So that no locator variable is not used

**Comment by mskelton** [comment]
This feels like quite an edge case. I've been thinking about this for a bit and I don't think it really makes sense to include in the plugin. Going to close as not planned.

**Comment by unlikelyzero** [comment]
@mskelton understood

**Comment by unlikelyzero** [comment]
@mskelton this ticket was implicitly closed by https://github.com/playwright-community/eslint-plugin-playwright/pull/315
