### ISSUE TITLE
[feature]: Provide a command line option to "check" and "fix" issues so that it can be used with pre-commit hooks and become more useful.

### ISSUE THREAD

**Issue by PramodKumarYadav** [playwright-community/eslint-plugin-playwright#208]
### Issue
I found the Plugin to be very useful but it currently only show issues in IDE. If I commit a file with issues hidden in multiple files, it has no problem committing them.

### Suggestion
Provide command line options to _check_ and _fix_ (fixable issues) so that those commands can be added with pre-commit hooks and can be run together with other linting checks to improve tests.

**Comment by PramodKumarYadav** [comment]
I realised that the issues were only non-blocking for the files that were already committed before the rules were implemented. For a new file, the errors and warnings were blocking in nature. 

I also realised that there is no separate command for fixing issues except the eslint command i.e.  "npx eslint . --fix". It is good to mention that in the readme file. 

Apart from that it would be good to add more examples of which settings can be overriden and how in readme file apart from additionalAssertFunctionNames. I wanted to change the level of few settings from warning to error or vice versa but couldnt get them to work. I am using the `.eslintrc.cjs` file format.

**Comment by mskelton** [comment]
It doesn't make sense for this plugin to document everything about how ESLint works. That would be a huge maintenance burden if every single ESLint plugin had to do so. If you want to know how ESLint works and it's available command line options, their docs are great, read them.

As for settings, everything is well documented.  Each rule has a full page of documentation which is linked to from the readme. `additionalAssertFunctionNames` is a global setting which is why it's included in the readme.

I'm closing this issue as there is nothing actionable for this plugin.

**Comment by PramodKumarYadav** [comment]
> d. Each rule has a full page of documentation which is linked to from the readme. `additionalAssertFunctionNames` is a global setting which is why it's included in the readme.
> 
> I'm closing this issue as there is nothing actionable for this plugin.

Hmmm, okay. I am coming from a decent Java background but am completely new to the TypeScript + Playwright eco system. I migrated because I love what you guys have done with Playwright and Typescript.

In fact, I do love reading official documentation and read the complete user guide for Playwright, Prettier and typescript-eslint so far. The reason I am mentioning this is, even after all this I was lost for some time just because I am new to this eco system. Imagine how it will be for users, who dont take the efforts to read official docs?

One approach could be to say, screw them, they didnt read the docs but if we want to make more and more users to migrate to playwright, another approach could be to make it a little easier for new users to onboard and if that means adding a little redundancy with one or two lines of information, its not a bad idea after all?

P.S: The setting options are all available on GitHub and I both read all of those options and even tried to override them from my local machine to see if that works. Only after I was not able to succed I asked if it could be a good idea to take just one setting and show how to override it from the project. 

If you still think its a terrible idea, then I wouldn't press it further. Cheers and kudos again for making a great product and also this plugin - which I love :).

**Comment by mskelton** [comment]
@PramodKumarYadav Did you read the ESLint docs? You mentioned the Playwright, Prettier, and TypeScript-ESLint docs, but if you never mentioned reading the actual ESLint docs.

If you look at the many other ESLint plugins that are available, you will find that among the most popular plugins, none of them give step by step instructions about using the `--fix` option, using commit hooks, etc. They show how to use the plugin itself, not ESLint. I'm very firm on this being correct, it is not the responsibility of a plugin author to teach users how to use ESLint itself.

It **is** however the responsibility of plugin authors to make sure that you can easily use the plugin, which I think we have done well in this plugin given that we have extensive documentation for each rule as well as extensive documentation on setting up the plugin in the README.

It's not that we are saying to users "screw you" if you don't read the docs. Again, it's about what the plugin controls and therefore needs to document. Regarding the point about getting more people to migrate to Playwright, as a community maintained plugin, that's not really something I'm worried about. If users choose Playwright great, if not great. My goal in maintaining this project is to provide the best possible lint rules when using Playwright. My goal is not to get people to migrate away from Cypress, Selenium, Puppeteer, etc.

Hope this context helps. Maintaining open source software is a constant battle of priorities and opinions, as a maintainer it's about getting the balance right, and sadly that doesn't always please everyone.

**Comment by PramodKumarYadav** [comment]
> @PramodKumarYadav Did you read the ESLint docs? You mentioned the Playwright, Prettier, and TypeScript-ESLint docs, but if you never mentioned reading the actual ESLint docs.
> 
> If you look at the many other ESLint plugins that are available, you will find that among the most popular plugins, none of them give step by step instructions about using the `--fix` option, using commit hooks, etc. They show how to use the plugin itself, not ESLint. I'm very firm on this being correct, it is not the responsibility of a plugin author to teach users how to use ESLint itself.
> 
> It **is** however the responsibility of plugin authors to make sure that you can easily use the plugin, which I think we have done well in this plugin given that we have extensive documentation for each rule as well as extensive documentation on setting up the plugin in the README.
> 
> It's not that we are saying to users "screw you" if you don't read the docs. Again, it's about what the plugin controls and therefore needs to document. Regarding the point about getting more people to migrate to Playwright, as a community maintained plugin, that's not really something I'm worried about. If users choose Playwright great, if not great. My goal in maintaining this project is to provide the best possible lint rules when using Playwright. My goal is not to get people to migrate away from Cypress, Selenium, Puppeteer, etc.
> 
> Hope this context helps. Maintaining open source software is a constant battle of priorities and opinions, as a maintainer it's about getting the balance right, and sadly that doesn't always please everyone.

@mskelton : Okay. I hear you. I started reading ESLint docs but went ahead to read TypeScript-ESLint docs when I realised for typescript those were the relevant ones; But taking your advice, I will finish the ESLint docs too.

I can still use some pointers with overriding settings. Lets say if I want to override a particular rule setting from playwright-pugin (example this one: https://github.com/playwright-community/eslint-plugin-playwright/blob/main/docs/rules/no-useless-not.md), where can I find an example of this? 

Is it somewhere in this project or mentioned on the ESLint docs?

**Comment by mskelton** [comment]
You are probably looking for this: https://eslint.org/docs/latest/use/configure/rules#disabling-rules
