### ISSUE TITLE
`eslint-plugin-playwright` errors over 'playwright/no-wait-for-selector' rule in v 1.0.1

### ISSUE THREAD

**Issue by ror-y** [playwright-community/eslint-plugin-playwright#211]
I have just installed `eslint-plugin-playwright` to its latest version 1.0.1.

With the rule `'playwright/no-wait-for-selector': 'error'` in my eslint rules, I get the eslint error:

```
ESLint: Definition for rule 'playwright/no-wait-for-selector' was not found.(playwright/no-wait-for-selector)
```

I have many other rules in my config and none of them are causing eslint errors.

The rule was introduced recently in [0.22.0](https://github.com/playwright-community/eslint-plugin-playwright/releases/tag/v0.22.0), and I've checked through the source code and can't find an issue with the implementation of the rule.

Anyone know what the problem could be?

**Comment by mskelton** [comment]
I can't reproduce this, can you create a reproduction repo or code sandbox?

**Comment by ror-y** [comment]
I think this was some sort of caching issue, it's fine for me now after nuking node_modules and package-lock. Thanks anyway
