### ISSUE TITLE
Use of `expect()` inside of page objects

### ISSUE THREAD

**Issue by vladkrasn** [playwright-community/eslint-plugin-playwright#237]
Officially suggested Page Object Model implementation (https://playwright.dev/docs/pom), as well as many guides online make use of expects inside of POM methods. At the same time, this plugin has at least two recommended rules that conflict with that approach - `expect-expect` and `no-standalone-expect`. 

I feel like there's no way to reconcile this, am I wrong?

**Comment by mskelton** [comment]
@vladkrasn In my opinion, placing expect calls inside of page object methods is an anti-pattern. The purpose of rules like `expect-expect` and `no-standalone-expect` is to encourage developers to make expectations clear in their tests. When you start hiding them in page object methods, your tests can include implicit assertions that are difficult to understand when reading tests.

If you want to use expect in page objects, my recommendation is to disable those rules for the file path where you place your page objects.

**Comment by vladkrasn** [comment]
It's just since there's a goal to put this plugin into the official playwright docs and whatnot, it's weird that **_by default_** it contradicts an officially suggested approach to such an important concept as POMs.

Plus it does seem to me that POMs want to offload a decent chunk of the logic from tests to classes.

**Comment by mskelton** [comment]
The use case of `expect` in page objects has been fixed, though I would still caution users against overusing that pattern.
