### ISSUE TITLE
Missing Playwright matchers in rules from latest releases`

### ISSUE THREAD

**Issue by vigneshrajsb** [playwright-community/eslint-plugin-playwright#24]
### What
The `playwrightTestMatchers` rules list has missing matchers from `Playwright` listed here https://playwright.dev/docs/test-assertions#

Here are the list of missing matchers that have to be added to the rules
```
  "toHaveAttribute",
  "toHaveCount",
  "toHaveJSProperty",
  "toHaveURL",
```

I can send a PR if needed.

Thanks for the lint plugin and it is super useful when most of our UI tests that are contributed by application engineers who might miss `await`ing in the tests

**Comment by mskelton** [comment]
Good catch!  I've opened a PR to add the missing matchers.
