### ISSUE TITLE
Title must be a string for string variables

### ISSUE THREAD

**Issue by abigailarmijo** [playwright-community/eslint-plugin-playwright#243]
Hi! I have some variable to reuse the step description that is a string but the aslant shows error.
```
const stepDescription = 'My description';
    await test.step(stepDescription, async () => {
})
```

**Comment by mskelton** [comment]
This behavior is intentional.

https://github.com/playwright-community/eslint-plugin-playwright/blob/main/docs/rules/valid-title.md#titlemustbestring

You can disable the `titleMustBeString` error using the `ignoreTypeOfDescribeName` and `ignoreTypeOfTestName` options.

```json
{
  "rules": {
    "playwright/valid-title": [
      "error",
      {
        "ignoreTypeOfTestName": true
      }
    ]
  }
}
```
