### ISSUE TITLE
`no-standalone-expect`: Allow defining functions which are treated as test functions

### ISSUE THREAD

**Issue by sevesalm** [playwright-community/eslint-plugin-playwright#244]
`jest/no-standalone-expect` has a configuration option `additionalTestBlockFunctions` which allows you to list functions which will be treated as test functions.  This didn't seem to work with `playwright/no-standalone-expect` so I propose you add it too to make this a more usable linting rule.

https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-standalone-expect.md

**Comment by mskelton** [comment]
@sevesalm While we don't support `additionalTestBlockFunctions`, we do support global test aliases which is what I would recommend for your use case.

https://github.com/playwright-community/eslint-plugin-playwright#aliased-playwright-globals
