### ISSUE TITLE
Rule `require-hook` should allow `test.use`

### ISSUE THREAD

**Issue by aarongoldenthal** [playwright-community/eslint-plugin-playwright#248]
Rule `require-hook` fails for a `test.use` used at the top level. Per [the documentation](https://playwright.dev/docs/api/class-test#test-use) `test.use` causes an error within a `beforeEach` or `beforeAll` hook (specifically - _Error: Playwright Test did not expect test.use() to be called here_), so it should be added to the allowed top level expressions in `require-hook`.

**Comment by mskelton** [comment]
This is already fixed in the latest version.

https://github.com/playwright-community/eslint-plugin-playwright/releases/tag/v1.3.1
