### ISSUE TITLE
Second argument must be functioneslintplaywright/valid-describe-callback

### ISSUE THREAD

**Issue by costa-collibra** [playwright-community/eslint-plugin-playwright#272]
When I add tags to the describe block like this:

```typescript
test.describe('Workflows', { tag: ['@workflows', '@nightly'] }, () => {
```

I get the following error

Second argument must be functioneslint[playwright/valid-describe-callback](https://github.com/playwright-community/eslint-plugin-playwright/tree/main/docs/rules/valid-describe-callback.md)

But this is now valid way of tagging so does this plugin need updating?

**Comment by costa-collibra** [comment]
@mskelton I am using the latest version but still seeing the error

**Comment by mskelton** [comment]
Did you reload your editor after updating to the latest version?

**Comment by costa-collibra** [comment]
Yes, I restarted VSCode and the error pops back up

**Comment by costa-collibra** [comment]
figured it out its the async on the describe

**Comment by mskelton** [comment]
Going to reopen since the error message might be wrong

**Comment by mskelton** [comment]
Test case added https://github.com/playwright-community/eslint-plugin-playwright/commit/ae780457
