### ISSUE TITLE
ESLint: Unexpected return statement in describe callback(playwright/valid-describe-callback) when use group tests

### ISSUE THREAD

**Issue by mr-anton-t** [playwright-community/eslint-plugin-playwright#274]
Hi 
I see the error `ESLint: Unexpected return statement in describe callback(playwright/valid-describe-callback)` after updating  to the last version (1.5.2)

test.mobile.list.ts
```TS
// ...

const product = 'mobile';
test.describe('group',  () => group(product));
```

group.spec.ts
```TS
 // ...

export function group(product: string )  {
  test('1.1', async ({ page }) => {
    // ...
  });

  test('1.2',  async ({ page }) => {
    // ...
  });
}
```

Please add this option to playwright/valid-describe-callback

**Comment by mskelton** [comment]
While I wouldn't recommend the way you are writing your tests, just add brackets to your describe callback and that will fix the error.

```js
test.describe('group',  () => {
  group(product)
});
```
