### ISSUE TITLE
Component testing ESLint rules

### ISSUE THREAD

**Issue by sand4rt** [playwright-community/eslint-plugin-playwright#298]
It's probably a lot of work, but it would be nice to have ESLint rules for [Playwright Component Testing](https://playwright.dev/docs/test-components). In this context, the [type MountOptions](https://github.com/microsoft/playwright/blob/2ae2fb421c6b6ec115721a8b0a5215442e5411c3/packages/playwright-ct-vue/index.d.ts#L31-L36), including the props of the components, are serialised and sent to the browser. This imposes certain limitations, as not all types can be serialised _(e.g., `class`, `Set`, `Map` and `Symbol()`)_. The ESLint plugin could provide error messages for these limitations.

example:

```jsx
// ClassAsProp.jsx
export function ClassAsProp(props) {
  return <div>{props.stuff.say()}</div>;
}
```

```jsx
// ClassAsProp.test.jsx
import { expect, test } from '@playwright/experimental-ct-react';
import { ClassAsProp } from './ClassAsProp';

test('class as prop', async ({ mount }) => {
  class Stuff { say() { return 'hello'; } }
  const stuff = new Stuff();
  const component = await mount(<ClassAsProp stuff={stuff} />); // <--- `stuff` is not a serialisable, create a story wrapper instead: https://playwright.dev/docs/test-components#test-stories
  await expect(component).toContainText("hello");
});
```

[Qwik](https://qwik.dev/docs/advanced/eslint/#valid-lexical-scope) has similar limitations/rules and has a `valid-lexical-scope` ESLint rule to address this, as seen in the `invalid-capture-.....tsx` files: [QwickJS valid-lexical-scope rule example](https://github.com/QwikDev/qwik/blob/c53e8a552782e4924b339675039fa0735c25b794/packages/eslint-plugin-qwik/tests/valid-lexical-scope/invalid-capture-enum.tsx#L2-L15).

Testing Library also offers a few useful component testing ESLint rules:

- https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-render-in-lifecycle.md ~~_(depends on https://github.com/microsoft/playwright/issues/31339)_~~

- https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/render-result-naming-convention.md

@pavelfeldman WDYT?

**Comment by mskelton** [comment]
This kind of logic is very difficult without type information, which this plugin does not, nor do I have plans for it to use type information.

I'm going to close as I don't think this fits the current plans of this plugin.
