### ISSUE TITLE
playwright/missing-playwright-await error on already awaited poll

### ISSUE THREAD

**Issue by ValorHeart** [playwright-community/eslint-plugin-playwright#311]
Seems like the .catch causes this error
<img width="1247" alt="image" src="https://github.com/user-attachments/assets/eeba81b7-4fe0-48ab-bfa9-a24112093793">

**Comment by mskelton** [comment]
This code example is insanely complex and can most certainly be simplified. Just use a `toHaveText` matcher with a locator.
