### ISSUE TITLE
ignoreTypeOfStepName dont work with  ignoreTypeOfStepName

### ISSUE THREAD

**Issue by mrozwat** [playwright-community/eslint-plugin-playwright#321]
` rules: {
          'playwright/valid-title': [
            'error',
            {
              ignoreTypeOfStepName: true,
              mustMatch: '^QATASK-T\\d+:\\s.+\\S$',
            },
          ],`

 "eslint-plugin-playwright": "1.6.2",

Oops! Something went wrong! :(
ESLint: 7.32.0
Error: .eslintrc.js#overrides[3]:
        Configuration for rule "playwright/valid-title" is invalid:
        Value {"ignoreTypeOfStepName":true,"mustMatch":"^QATASK-T\\d+:\\s.+\\S$","ignoreSpaces":false,"ignoreTypeOfDescribeName":false,"ignoreTypeOfTestName":false} should NOT have additional properties.

If I set any other variable except ignoreTypeOfStepName then everything works well. However, by default it seems to be false since the lines in test.step are not ignored
![image](https://github.com/user-attachments/assets/72a789c0-6890-4f9b-b67d-42026c30fd78)

**Comment by mskelton** [comment]
If you are going to submit an issue, please give us maintainers the courtesy of at least formatting the code and error properly.

Can you create a reproduction repo? This is not an issue with the plugin, it's configured properly so it's something with your setup, likely outdated packages.

**Comment by mrozwat** [comment]
I apologize for the formatting. It turned out that npm contains a package released 5 months ago and it does not have this functionality since it appeared only a month ago

**Comment by mskelton** [comment]
@mrozwat I cut a new release this morning, should be available soon.
