### ISSUE TITLE
[request] playwright/valid-title - option to disable duplicatePrefix rule

### ISSUE THREAD

**Issue by dylang** [playwright-community/eslint-plugin-playwright#325]
We're fine with duplicate prefixes, it helps with scanning and sorting the results.

I thought this would work, but it doesn't:

```ts
'playwright/valid-title': ['error', { duplicatePrefix: false }]
```

**Comment by mskelton** [comment]
This is not configurable, and I don't plan to make it so.

**Comment by mskelton** [comment]
It's unnecessary, tests do not read as naturally, and adds extra configuration that would require maintaining.

**Comment by dylang** [comment]
Thank you for the quick reply and great work on this plugin.

The team is working on removing the duplication. 

The reason for the duplication is that they copy/paste the test title from our test plan.

**Comment by mskelton** [comment]
The rule is autofixable, so when you press save in your editor, it will automatically remove the prefixes.
