### ISSUE TITLE
Documentation for default levels

### ISSUE THREAD

**Issue by stevendarby** [playwright-community/eslint-plugin-playwright#334]
Hello, for the recommended set of rules, is there an easy reference for their default level (e.g. warn or error)?

I _think_ I can check the source here:
https://github.com/playwright-community/eslint-plugin-playwright/blob/c067ad203fba4617a9e04ee610dc0ee3d1b40f04/src/index.ts#L105-L133

But perhaps it would be nice if this was also in the table in the readme

**Comment by mskelton** [comment]
I'm not interested in maintaining this list in two places, code and docs.  Closing as won't do

**Comment by stevendarby** [comment]
Fair enough @mskelton, just to confirm though, those are the recommended rules with their defaults, right?

If so, maybe it could self document a little better - perhaps just a comment nearby? I kind of stumbled on this when searching the code and not really familiar with eslint rules code! Thanks.

**Comment by mskelton** [comment]
Yes, those are the default levels for the recommended rules.

Feel free to open a PR to add a comment, happy to add that in.
