### ISSUE TITLE
Publish new rules

### ISSUE THREAD

**Issue by elaichenkov** [playwright-community/eslint-plugin-playwright#49]
**Description:**
This month we've added a few new rules. So, it'd be nice to have them in the upcoming release.

**To do:**

- [x] - Create release notes
- [x] - Publish updates to the npm
- [ ] - Update documentation to add section with how to disable/enable specific rule, add rules table

**Comment by mxschmitt** [comment]
I think we are ready now to publish a new version `v0.9.0`, GitHub generated the following change log which we can optimise:

```
## What's Changed
* Add tests for `expect.soft` by @mskelton in https://github.com/playwright-community/eslint-plugin-playwright/pull/37
* build(deps): bump minimist from 1.2.5 to 1.2.6 by @dependabot in https://github.com/playwright-community/eslint-plugin-playwright/pull/38
* Add new "no element handle" rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/40
* devops: add NPM publish workflow by @mxschmitt in https://github.com/playwright-community/eslint-plugin-playwright/pull/42
* Add no eval rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/41
* Add new "noFocusedTest" rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/44
* Add new "noWaitForTimeout" rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/46
* Add new "noSkippedTest" rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/45
* Utils: add runRuleTester helper function by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/48
* Feature add no force option rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/47

## New Contributors
* @elaichenkov made their first contribution in https://github.com/playwright-community/eslint-plugin-playwright/pull/40

**Full Changelog**: https://github.com/playwright-community/eslint-plugin-playwright/compare/v0.8.0...v0.9.0
```

Or rendered:

## What's Changed
* Add tests for `expect.soft` by @mskelton in https://github.com/playwright-community/eslint-plugin-playwright/pull/37
* build(deps): bump minimist from 1.2.5 to 1.2.6 by @dependabot in https://github.com/playwright-community/eslint-plugin-playwright/pull/38
* Add new "no element handle" rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/40
* devops: add NPM publish workflow by @mxschmitt in https://github.com/playwright-community/eslint-plugin-playwright/pull/42
* Add no eval rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/41
* Add new "noFocusedTest" rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/44
* Add new "noWaitForTimeout" rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/46
* Add new "noSkippedTest" rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/45
* Utils: add runRuleTester helper function by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/48
* Feature add no force option rule by @elaichenkov in https://github.com/playwright-community/eslint-plugin-playwright/pull/47

## New Contributors
* @elaichenkov made their first contribution in https://github.com/playwright-community/eslint-plugin-playwright/pull/40

**Full Changelog**: https://github.com/playwright-community/eslint-plugin-playwright/compare/v0.8.0...v0.9.0

**Comment by elaichenkov** [comment]
Let's :shipit:

**Comment by mxschmitt** [comment]
Version 0.9.0 is live, closing this issue for now, we can follow up with better docs and whats enabled / disabled / warned by default: https://www.npmjs.com/package/eslint-plugin-playwright

Thank you!
