### ISSUE TITLE
`v0.9.0` Playwright shows false positive for `expect` assertions of Jest with same name (e.g. `toBeVisible`)

### ISSUE THREAD

**Issue by bennettdams** [playwright-community/eslint-plugin-playwright#54]
_Tested with `v0.9.0`_

I'm using Jest tests (normal unit/integration tests) and Playwright (with the Playwright runner, not Jest) in the same repo. 

There are some `expect` assertions with the same name used by Jest and Playwright.
When using such an assertion in a Jest test (with a name that also exists at the Playwright runner's `expect`, e.g. `toBeVisible`), this plugin will show errors for the Jest assertion:

![image](https://user-images.githubusercontent.com/29319414/168870687-cd923c75-d56f-47e3-ab7a-8afdad63f272.png)

---

I understand that I can overwrite rules in my ESLint config and disable this plugin for my Jest tests, but I thought that it would be nice if the plugin brings this functionality out of the box.

**Comment by mskelton** [comment]
Not sure there is a great way to solve this.  Your solution of disabling the plugin for your Jest tests is what I'd recommend, or inverting it such that you only enable it on your Playwright test folder.

**Comment by bennettdams** [comment]
Okay, thanks, I just wanted to ask officially.
