### ISSUE TITLE
Expect.soft assertions only

### ISSUE THREAD

**Issue by unlikelyzero** [playwright-community/eslint-plugin-playwright#60]
It would be great to have a rule to enforce expect.soft assertions. I've found that they've been a great way to isolate failure in tests but find it difficult to keep track of them during code reviews.

**Comment by mskelton** [comment]
Hmm.  @mxschmitt what do you think?  Feels like a pretty odd rule to enforce IMO, in my experience soft assertions are a infrequently used feature that comes in handy in a few instances, but certainly not everywhere.

**Comment by unlikelyzero** [comment]
@mskelton we're encouraging folks to write "longer" tests given that most of our test duration is spent setting up certain contexts and we're recording the tracefiles which give "pin point accuracy" for test failure.

**Comment by mskelton** [comment]
Been a while, but I have a PR to fix this finally 🙂
