### ISSUE TITLE
[Enhancement] Allow customMatchers for "no-focused-test"

### ISSUE THREAD

**Issue by FlorianChristie** [playwright-community/eslint-plugin-playwright#61]
In our code, we usually define custom test fixtures for different tests. For example, instead of just using `test()` we have a custom test fixture called `guiTest()`. Currently, the "no-focused-test" option only checks for `test.only()`, but no other custom matchers are considered. It would be great, if one could define customMatchers so that also these throw an error during linting.

**Comment by mskelton** [comment]
Why do you need a wrapper around `test` for fixtures?  Only the fixtures you use in a test are created, so if you define all the fixtures for your entire project and then import those, it will work the same way.  For example.

```ts
// fixtures.ts
import { test as base } from '@playwright/test'

export const test = base.extend({
  myFixture: async ({ page }, use) => {
     // do something
  },
})
```

Then just import `test` from there.

```diff
-import { test } from '@playwright/test'
+import { test } from './fixtures'
```
