### ISSUE TITLE
jest rules being applied to playwright tests

### ISSUE THREAD

**Issue by wesyao** [playwright-community/eslint-plugin-playwright#66]
Hello!

I'm just looking for some guidance on how to manage both eslint rules for playwright test and jest within the same project.  I'm using playwright test to run e2e tests and jest to run regular unit/integration tests. I'm having jest rules applying to my playwright tests.

.eslintrc.js
```
...
    extends: [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:jest/recommended",
        "plugin:jest/style",
        "plugin:testing-library/react",
        "plugin:playwright/playwright-test",
    ],
...
```

error:
```
   7:9  error  Expect must be inside of a test block  jest/no-standalone-expect
  13:9  error  Expect must be inside of a test block  jest/no-standalone-expect
  19:9  error  Expect must be inside of a test block  jest/no-standalone-expect
```

What is the recommended way to manage these rules between the two test runners? I suspect it's to use the override property, but I wanted to see what other people thought.

Thank You!

**Comment by mskelton** [comment]
Yes, conditionally enabling each plugin using the `overrides` property would be the correct solution.
