### ISSUE TITLE
Parity with `eslint-plugin-jest`

### ISSUE THREAD

**Issue by unlikelyzero** [playwright-community/eslint-plugin-playwright#67]
We're establishing coding practices for our e2e suite before opening it up to the public. Generally, we're looking to *enforce* these code practices wherever possible _and would likely need most of the rules from the Jest ESLint plugin_.

- [x] #143
- [x] #220
- [x] #221
- [x] #219
- [x] #218
- [x] #232
- [x] #91
- [x] #215
- [x] #230
- [x] #231
- [x] #216
- [x] #217
- [x] #85
- [x] #103
- [x] #104
- [x] #144
- [x] #93
- [x] #233
- [x] #234
- [x] #84
- [x] #236
- [x] #235
- [x] [valid-title](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/valid-title.md)

**Probably don't need these**

- [x] [no-test-return-statement](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-test-return-statement.md)
- [x] [no-large-snapshots](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-large-snapshots.md)

**Comment by unlikelyzero** [comment]
@mskelton hey, would you mind undoing the reformatting? I was using it to visual scan for changes from the jest dir. I had 2 i needed to add from their recent deployment

**Comment by mskelton** [comment]
@unlikelyzero The reason I changed it was so we can use GitHub's feature to convert a list item into an issue for tracking.  Will make it much easier to see progress as we work through the list creating and closing issues for each of these features.

Can we just add the new rules to the end of the list?

**Comment by unlikelyzero** [comment]
@mskelton in this case, I think we should have a near-synchronous discussion on the the purpose of this ticket. this ticket initially was supposed to be a one-time audit and a conversation about what is applicable to this project. I think all of that work has been undone

**Comment by mskelton** [comment]
After a year and a half of opening this issue, I'm happy to report I've finished the last of the remaining lint rules!
