### ISSUE TITLE
"valid-expect" should not error on `expect().nothing();`

### ISSUE THREAD

**Issue by DerZyklop** [playwright-community/eslint-plugin-playwright#99]
[The rule](https://github.com/playwright-community/eslint-plugin-playwright/blob/main/docs/rules/valid-expect.md) complains about `expect();` which is fine, because this looks like wrong code. It has no effect.

But if someone writes `expect().nothing();`, he/she consciously wants to expect nothing to happen. So this should not be an error.

**Comment by mskelton** [comment]
I'm not sure I follow.  First of all, `expect().nothing()` is not a valid Playwright or Jest matcher, so that statement would fail.  Second, when would you ever need to expect nothing?  That's seems kind of pointless.
